### ISSUE TITLE
ignore missed semicolons

### ISSUE THREAD

**Issue by SailorMax** [phpmyadmin/sql-parser#10]
test sql:
```sql
START TRANSACTION

ALTER TABLE `tbl` CHANGE `uid` `uid` INT( 10 ) UNSIGNED NOT NULL AUTO_INCREMENT

ALTER TABLE `tbl` CHANGE `field_1` `field_2` INT( 10 ) UNSIGNED NOT NULL

COMMIT
```

After each line we missed semicolons, but sql-parser don't see any errors.
Test code same as in #9

**Comment by udan11** [comment]
The `ALTER` statement has not been properly implemented and that's why it can't check when the next query starts. I hope to fix it soon.
