### ISSUE TITLE
The value should not be altered

### ISSUE THREAD

**Issue by bigfoot90** [phpmyadmin/sql-parser#109]
If you format this query with `cli` style
```sql
select 'text\x1b[33mcolor-inj' from tbl
```
the string is currently being altered, and `\x1b` is converted in `\x1B`

https://github.com/phpmyadmin/sql-parser/blob/master/tests/Utils/FormatterTest.php#L136

**Expected**
The value should not be altered because it's a string

**Comment by nijel** [comment]
There is no such thing as upper/lower case in the original string - it's hex encoded byte which is parsed by PHP and passed as binary value to the parser.

If you pass `\x1b` as string, it is of course kept as is:

```
$ ./bin/highlight-query --query "select 'text\x1b[33mcolor-inj' from tbl"
SELECT
  'text\x1b[33mcolor-inj'
FROM
  tbl
```

**Comment by bigfoot90** [comment]
@nijel Prease see the test, the code doesn't lie!
https://github.com/phpmyadmin/sql-parser/blob/master/tests/Utils/FormatterTest.php#L350

**Input**
`select 'text\x1b[33mcolor-inj' from tbl`
**Expected**
`\x1b[35mSELECT\n  \x1b[91m'text\\x1b[33mcolor-inj'\n\x1b[35mFROM\n  \x1b[39mtbl\x1b[0m`
**Actual**
`\x1b[35mSELECT\n  \x1b[91m'text\\x1B[33mcolor-inj'\n\x1b[35mFROM\n  \x1b[39mtbl\x1b[0m`

Try to correct this line, and the test will fail.

**Comment by nijel** [comment]
Yes it will, but the `\x1b` is interpreted by PHP and is stored as **byte** in the string, it does not matter how it's written there, in the end it's stored string as escape char.

To check that, create following PHP file:

```php
<?php
echo "select 'text\x1b[33mcolor-inj' from tbl\n";
?>
```

And execute it by PHP:

```console
$ php /tmp/test.php
select 'textcolor-inj' from tbl
```

As you can see there is **no** `\x1b` in the string!

**Comment by bigfoot90** [comment]
I'know, but I don't why the test is different from the expecting string?
Also, I don't realize how this is possible.

**My fear is that:**
If it behaves differently in phpunit tests, then it can behave unexpectedly in the real life too.
`PhpUnit` is php too, nothing different should go.

**Comment by bigfoot90** [comment]
OK, I understand it now.
Both `\x1b` and `\x1B` are the same character after encoding.

Closing  ;-)
