### ISSUE TITLE
broken error position, because of unsupported ALTER

### ISSUE THREAD

**Issue by MaxiBul** [phpmyadmin/sql-parser#11]
I know about not supported ALTER, but current status return errors pointer on correct previous queries.

Sample:
``` MySQL
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";
SELECT * FROM `foo` WHERE `fld` = "фошафщцукщжшрцфгшкрцуг";


CREATE TABLE `tb_` (`rel_uid` BIGINT UNSIGNED NOT NULL ,
`custom_field_uid` INT UNSIGNED NOT NULL ,
`related_object_uid` BIGINT UNSIGNED NOT NULL ,
`value` VARCHAR( 255 ) NOT NULL ,
INDEX ( `related_object_uid` )
) ENGINE = InnoDB;

ALTER TABLE `tb_` ADD PRIMARY KEY ( `rel_uid` , `custom_field_uid` ) ;

ALTER TABLE `tb_` DROP INDEX `w_rel` ,
ADD INDEX `w_rel` ( `w_type_uid` , `related_object_uid` , `w_uid` );
```

EXP: error position = start of unrecognized operation (start of ALTER): line 24 col 1 and line 26 col 1.

ACT: Checking this code return errors about ALTER ("unrecognized alter operation"), but line and column position in SELECT and CREATE queries: line 14 col 80 and line 18 col 37.

Looks like pointer coordinates can be shifted by the code without any restrictions.

**Comment by udan11** [comment]
Fixed the alter operation issue in 8a1011e97497cbecbfb7cf9ef36146aaf81a1486.

Regarding to the other issue, those positions are correct, somehow. The query contains a couple of UTF-8 characters that occupy more than one byte and the character position will be different than the byte position.

I am not sure if I made myself clear so let's consider the following query: `????+` where `?` is a 2-byte character and the `+` is a 1-byte character which causes an error. The position of the error will be reported at position 4, even though the character `+` is the 8-th byte.

If you are using the linting feature of phpMyAdmin, I already sent a pull request.
