### ISSUE TITLE
Empty lines if formatting in text style (the default)

### ISSUE THREAD

**Issue by bigfoot90** [phpmyadmin/sql-parser#110]
If you're formatting a query in `text` style (the *default* if you do not specifiy) you are getting ampty lines only.

**Example query**
```sql
SELECT DISTINCT * FROM tbl1 INNER JOIN tbl2 ON id1 = id2 WHERE condition
```

**Expected result**
```sql
SELECT DISTINCT 
    *
FROM
    tbl1
INNER JOIN tbl2 ON id1 = id2
WHERE
    condition
```

**Actual result**
```
\n
      \n
\n
    \n
\n
\n
      \n
```

**Comment by nijel** [comment]
Already fixed in 5f79069a372e6e817c9989160b6f533ccf92b5a5.
