### ISSUE TITLE
Dependency of phpmyadmin/motranslator

### ISSUE THREAD

**Issue by bigfoot90** [phpmyadmin/sql-parser#129]
As from version `4.1.0` https://github.com/phpmyadmin/sql-parser/commit/438ac0bd5751cfc7582c03768d0149404004bb15#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R20
You are requesting `phpmyadmin/motranslator` as a dependency.

I'm using SqlParser in my standalone project (outside of `phpmyadmin`) mainly as a formatter tool

**My question is:**
Is this really a hard depencedependencyncy?
I think that's a dependency of `phpmyadmin/phpmyadmin` itself.
Can we [suggest installing](https://getcomposer.org/doc/04-schema.md#suggest) `motranslator` instead of requiring it?

**Comment by nijel** [comment]
Patches are welcome to make the dependency optional. It's used to localize error messages from the parser.

**Comment by nijel** [comment]
Also note there is one problem with suggests in composer - AFAIK there is no way to define which version you need, so you can easily end up with installed version with incompatible API.

**Comment by bigfoot90** [comment]
Right, composer does not have version requirements for suggestions, but have `conflict` where you can exclude the incompatible versions, in addition we can add a note in the `README.md`.

**Comment by nijel** [comment]
Okay, that would work as well.

The only part which needs to be adjusted is https://github.com/phpmyadmin/sql-parser/blob/master/src/Translator.php

**Comment by bigfoot90** [comment]
Ok, I can prepare a PR in the next days.

Can you show me how to use this `Translator` in a real life example? Please.

**Comment by nijel** [comment]
It just returns translated text, for example see https://github.com/phpmyadmin/sql-parser/blob/438ac0bd5751cfc7582c03768d0149404004bb15/src/Component.php#L43
