### ISSUE TITLE
some Components are missing a constructor

### ISSUE THREAD

**Issue by ccprog** [phpmyadmin/sql-parser#140]
with a public state:
- AlterOperation
- IntoKeyword
- JoinKeyword
- ParameterDefinition
- PartitionDefinition
- RenameOperation
- SetOperation

able to receive a TokensList, but currently without public state:
- Array2d
- ExpressionArray

UnionKeyword obviously does not have a state.

The individual need for them may differ, but it sure makes using the library for statement creation awkward.

**Comment by udan11** [comment]
See 84fbf25, 632696d, cb87e17, 7fd8add, ab1535d, 50f88fb.
