### ISSUE TITLE
Error using GROUP BY with PostgreSQL

### ISSUE THREAD

**Issue by JoseNetoooo** [phpmyadmin/sql-parser#154]
Hello everybody! I've been using sql-parser with postgresql. When I build the query and get the rawSql I see the following:
```sql
GROUP BY "created_at" ASC
```
...but PostgresSQL does not accept **ASC** after the **GROUP BY** keyword. Is there a way to avoid it? Or Is there anything I'm missing here?

Above we can see the build() function located in the Components/OrderKeyword.php class. This class is used by the **GROUP BY** keyword and always returns:

```php
$component->expr . ' ' . $component->type
```

```php
public static function build($component, array $options = array())
    {
        if (is_array($component)) {
            return implode(', ', $component);
        }

        return $component->expr . ' ' . $component->type;
    }
```

**Comment by JoseNetoooo** [comment]
[https://develdocs.phpmyadmin.net/sql-parser/source-class-PhpMyAdmin.SqlParser.Parser.html#349-552](The Parser class)

[https://develdocs.phpmyadmin.net/sql-parser/source-class-PhpMyAdmin.SqlParser.Components.OrderKeyword.html#14-140](The OrderKeyword class)

**Comment by nijel** [comment]
Neither MySQL does accept ASC/DESC here, it's bug in the parser that uses another component here...

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/sql-parser/pull/155 with few other fixes:

* 9bdebcf Document change for #154 and #155
* 4af06d2 Remove not used type arg from GROUP BY
* f18666a Merge commit '48d61a0c05316a25d9462379e79ff56d5e22a29c'
* 9837c18 Add (failing) test for building GROUP BY clause

**Comment by williamdes** [comment]
Using MariaDB 10.2 the query was valid https://github.com/phpmyadmin/sql-parser/commit/4af06d24b041e499fb0e75ab3a98caf9a91700ef#commitcomment-36623272
