### ISSUE TITLE
Partition by tables

### ISSUE THREAD

**Issue by Lapkritinis** [phpmyadmin/sql-parser#174]
There is mistype which fails to parse partitioned by tables.
It joins "partition P0Engine INNODB" together. I have reported this issue to phpmyadmin.

**Comment by nijel** [comment]
Can you please include complete failing query?

**Comment by Lapkritinis** [comment]
Proposed fix #176.

I have described issue here:
https://github.com/phpmyadmin/phpmyadmin/issues/13725

**Comment by Lapkritinis** [comment]
I thought it works (it does copy partitioned table now), but resulting table is without partitions, so it needs deeper investigation.

**Comment by nijel** [comment]
What version do you use? I've added tests in 078509e44d73a2d2b35da38d0ce4bcbb97f94bf8 and the do not indicate any problem...

**Comment by Lapkritinis** [comment]
Latest available: 4.7.4
PHP 7.1.10

**Comment by Lapkritinis** [comment]
Test you have added doesn't work in MySQL:

Static analysis:

1 errors were found during analysis.

Unrecognized statement type. (near "PARTITION" at position 209)
SQL query:

CREATE TABLE `ts` ( `id` int(11) DEFAULT NULL, `purchased` date DEFAULT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 PARTITION BY RANGE (YEAR(purchased)) SUBPARTITION BY HASH (TO_DAYS(purchased)) ( PARTITION p0 VALUES LESS THAN (1990) ( SUBPARTITION s0 ENGINE=InnoDB, SUBPARTITION s1 ENGINE=InnoDB ), PARTITION p1 VALUES LESS THAN (2000) ( SUBPARTITION s2 ENGINE=InnoDB, SUBPARTITION s3 ENGINE=InnoDB ), PARTITION p2 VALUES LESS THAN MAXVALUE ( SUBPARTITION s4 ENGINE=InnoDB, SUBPARTITION s5 ENGINE=InnoDB ) )

**Comment by nijel** [comment]
It works just fine for me on MariaDB 10.1.28. That's why I was asking what query is causing problems to you.

**Comment by Lapkritinis** [comment]
I have added this to test cases and it fails:

`CREATE TABLE `test` (
  `event_date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC
PARTITION BY HASH (TO_DAYS(event_date))
(PARTITION p0 ENGINE = InnoDB,
 PARTITION p1 ENGINE = InnoDB,
 PARTITION p2 ENGINE = InnoDB,
 PARTITION p3 ENGINE = InnoDB,
 PARTITION p4 ENGINE = InnoDB
 )`
