### ISSUE TITLE
wrong error row number

### ISSUE THREAD

**Issue by SailorMax** [phpmyadmin/sql-parser#177]
sample code:
``` mysql
SELECT 'выбор типа';
SELECT 1
#INSERT INTO tbl2 (name) VALUES (
	SELECT 1;
#);
```
(missed semicolon after second SELECT)

Currently parser return error:
```
test.sql (line 3, col 33): This type of clause was previously parsed. (near: SELECT)
#INSERT INTO tbl2 (name) VALUES (
                                ^
```

Expected: commented line can not has error pointer.

**Hint**: problem in UTF-8 russian string.

**Comment by nijel** [comment]
I'm not able to reproduce this. What version do you use? Do you have installed mbstring PHP extension?

**Comment by nijel** [comment]
Apparently you're using third party frontend which is causing this, I've filled the report there: https://github.com/cweiske/php-sqllint/issues/14

**Comment by SailorMax** [comment]
Problem was in my function. Don't know anything about php-sqllint.
Sorry.

**Comment by nijel** [comment]
Well the php-sqllint has exactly same bug :-).

Anyway I've clarified the documentation for position attribute in c0d374a
