### ISSUE TITLE
LOCK TABLES unrecognized

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/sql-parser#180]
The LOCK TABLES query is not recognized:

```
$ ./lint-query --query 'LOCK TABLES `foo` READ'
#1: Unrecognized statement type. (near "LOCK" at position 0)
```

See https://stackoverflow.com/questions/46898267/lock-tables-phpmyadmin-not-working

**Comment by nijel** [comment]
See https://dev.mysql.com/doc/refman/5.7/en/lock-tables.html for syntax.
