### ISSUE TITLE
creating table in query

### ISSUE THREAD

**Issue by Dave3991** [phpmyadmin/sql-parser#182]
```
CREATE TABLE db_name_import.`configuration` (
	`key` VARCHAR(64) NOT NULL DEFAULT '' COLLATE 'utf8_czech_ci',
	`value` VARCHAR(300) NULL DEFAULT NULL COLLATE 'utf8_czech_ci',
	`description` VARCHAR(2000) NULL DEFAULT NULL COLLATE 'utf8_czech_ci',
	PRIMARY KEY (`key`)
)
COLLATE='utf8_czech_ci'
ENGINE=MyISAM
;
```

syntax is OK - works in mariaDb, getting this errors

```
 Line 2, col 40 at "COLLATE": A comma or a closing bracket was expected.
 Line 3, col 18 at "300": Unexpected beginning of statement.
 Line 3, col 23 at "NULL": Unrecognized statement type.
```

**Comment by nijel** [comment]
The syntax is not ok according to [their documentation](https://mariadb.com/kb/en/library/create-table/#column-and-index-definitions), but as it works, we should support it as well...

**Comment by Dave3991** [comment]
this code was originaly generated by HeidiSQL

**Comment by nijel** [comment]
According to the docs (which were used to write the parser), the COLLATE should be next to type definition prior to any NULL clauses, but yes, it works...
