### ISSUE TITLE
Unrecognized data type near "POINT"

### ISSUE THREAD

**Issue by vrgomes** [phpmyadmin/sql-parser#185]
When executing this the phpmyadmin says Unrecognized data type. (near "POINT" at position 96)

CREATE TABLE 'EVENT' (
  'EVENT_ID' INT(11) NOT NULL AUTO_INCREMENT,
  'EVENT_COORDINATE' POINT DEFAULT NULL,
  'EVENT_GUID' BIGINT UNSIGNED DEFAULT NULL,
  PRIMARY KEY ('EVENT_ID')
) COLLATE='utf8_general_ci' ENGINE=INNODB AUTO_INCREMENT=1;

**Comment by nijel** [comment]
It validates just fine for me, what phpMyAdmin and/or SQL Parser version do you use?

```
$ ./bin/lint-query --query 'CREATE TABLE `EVENT` (
`EVENT_ID` INT(11) NOT NULL AUTO_INCREMENT,
`EVENT_COORDINATE` POINT DEFAULT NULL,
`EVENT_GUID` BIGINT UNSIGNED DEFAULT NULL,
PRIMARY KEY (`EVENT_ID`)
) COLLATE="utf8_general_ci" ENGINE=INNODB AUTO_INCREMENT=1;'
```

PS: You're using wrong quotes around field names, that might be source of your problems as well.

**Comment by vrgomes** [comment]
Hi yes you are right. It looks like it's the quotes. 
Greetings.
