### ISSUE TITLE
https://develdocs.phpmyadmin.net/ is broken

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/sql-parser#191]
@nijel 
https://develdocs.phpmyadmin.net/

https://github.com/phpmyadmin/sql-parser/blob/0302f26460e48273eb391327017520d6d9cf04d5/README.md#L25-L26

https://github.com/phpmyadmin/motranslator/blob/303e3d636704c59f971d05325cd9d18f03b41d81/README.md#L33-L34

**Comment by nijel** [comment]
Known issue, the problem is that the tool we use is not compatible with PHP 7 and our server now runs that, see https://github.com/phpmyadmin/scripts/issues/11
