### ISSUE TITLE
CREATE OR REPLACE VIEW build()s incorrectly

### ISSUE THREAD

**Issue by travisghansen** [phpmyadmin/sql-parser#204]
```
CREATE OR REPLACE VIEW
```
becomes
```
CREATE OR REPLACE=VIEW
```

**Comment by devenbansod** [comment]
@travisghansen I tried to add tests for building the CREATE OR REPLACE VIEW at #209  and they seem to pass with the expected output. 

Am I missing something?

**Comment by devenbansod** [comment]
@travisghansen closing this as it seems to be working as expected.

Please re-open if you find something misbehaving.

**Comment by travisghansen** [comment]
@devenbansod I updated `v4.2.4 => v4.2.5` and this appears to be resolved now.  So good for me.
