### ISSUE TITLE
[sql-parser] PURGE statement unrecognized

### ISSUE THREAD

**Issue by nikita65** [phpmyadmin/sql-parser#207]
Hello,
with version 4.8.3 and 4.8.4 I cannot use anymore this query into the "SQL" panel:
```sql
PURGE BINARY LOGS TO 'mylog-bin.123' 
```
just typing in "PURGE " raises the error after few seconds (even if PURGE is in the list of selectable statements that pops up when typing commands).

The supposed error says: "PURGE: Unrecognized statement type. (near PURGE)"

It looks like a parser error; it was working in version 3.x.x and it is working if used directly with command line "mysql" binary.

Thank you and keep up with your good/great work. Thumbs up..
Bye nIc

**Comment by devenbansod** [comment]
@williamdes @nikita65 I've made a PR to hopefully fix this at #208
