### ISSUE TITLE
Missing comma on ALTER TABLE with COLLATE and COLLATION

### ISSUE THREAD

**Issue by pszalko** [phpmyadmin/sql-parser#229]
Hi,

The following statement:

```sql
ALTER TABLE `place` CHANGE COLUMN `plc_location_type` `gplc_location_type` ENUM('LOCATION') CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL;
```
throws an exeception: "Missing comma before start of a new alter operation."

Looks like similar issue to #218

**Comment by pszalko** [comment]
When removed both `CHARACTER` and `COLLATE` part from SQL, parser works fine.
The following SQL **does not** throw an exception:
```sql
ALTER TABLE `place` CHANGE COLUMN `plc_location_type` `gplc_location_type` ENUM('LOCATION') NOT NULL;
```

**Comment by williamdes** [comment]
@devenbansod Can you please have a look ?

**Comment by araknv** [comment]
I am still facing this issue in `v4.9.4` for Query 
```ALTER table "tableName" CHANGE COLUMN "old_column_name" TO "new_column_name" ```

**Comment by williamdes** [comment]
This is because you are using the SQL mode `ANSI_QUOTES`
https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes

I think you should refer to https://github.com/phpmyadmin/sql-parser/issues/284 to follow any progress on this issue
