### ISSUE TITLE
Missing comma on ALTER TABLE with ENUM

### ISSUE THREAD

**Issue by MasterSalomon** [phpmyadmin/sql-parser#234]
Hi, 

the following statement:

```sql
ALTER TABLE `mail_template` CHANGE COLUMN `mtpl_group` `mtpl_group` ENUM('ORDER') NULL DEFAULT NULL ;
```

throws an exeception: "Missing comma before start of a new alter operation.".

When renamed 'ORDER' to 'TEST' parser works fine.

**Comment by niconoe-** [comment]
After a test, #485 fixes this. No matter the operation is a `MODIFY` or a `CHANGE`.
