### ISSUE TITLE
"enclosed by" is not recognized by the SQL parser

### ISSUE THREAD

**Issue by svaningelgem** [phpmyadmin/sql-parser#236]
### Describe the bug

"enclosed by" is not recognized by the SQL parser

### To Reproduce

1. Go to SQL window
2. Type for example:
```sql
SELECT a
into outfile '/tmp/temp.data' 
fields terminated by ',' enclosed by '"'
FROM sometable
```
3. no need to run it (but when you run it against an actual table, it works just fine on the MySQL server)

### Expected behavior

No error (no red cross at the left side)

### Observed behaviour

Red cross at the left + these messages:
- Unrecognised keyword. (near **enclosed by**)
- Unexpected token. (near '"')

**Comment by williamdes** [comment]
```
echo "SELECT a into outfile '/tmp/temp.data'  fields terminated by ',' enclosed by '\"' FROM sometable" | ./bin/lint-query 
#1: Unrecognized keyword. (near "enclosed by" at position 65)
#2: Unexpected token. (near "&#039;&quot;&#039;" at position 77)
```

**Comment by williamdes** [comment]
Okay, the bug in the code is about the casing of `fields`, use uppercase and it will be happy
