### ISSUE TITLE
add support to lint a *.sql file

### ISSUE THREAD

**Issue by staabm** [phpmyadmin/sql-parser#237]
would be great to have support for linting sql files.

that way we would be able to use this tool for linting purposes within a CI pipeline

**Comment by staabm** [comment]
Additionally/Alternatively it would be great to lint the stdin

**Comment by ibennetch** [comment]
Excellent idea.

This was implemented with #239.

This will be part of the next `sql-parser` release. I wonder if this is worth a major version release, jumping to version 5, or if we do a minor version increase to version 4.4. Any opinions from anyone?

**Comment by staabm** [comment]
Thank you guys. From my POV would a minor bump be sufficient (semver wise) - in case there are no other breaking changes in the pipeline

**Comment by staabm** [comment]
I just realized that in the changelog is mentioned that a lot of old PHP version will be dropped of support.

Therefore a new major version is a must

**Comment by ibennetch** [comment]
Oh, right, I was planning that anyway and had just forgotten for a moment.
We're looking to merge a few other feature-based pull requests before
pushing the new release, if we can get that done soon.

Thanks again!

**Comment by staabm** [comment]
Any chance we get a new release soon?
