### ISSUE TITLE
Validation of simulated query fails

### ISSUE THREAD

**Issue by peterkahl** [phpmyadmin/sql-parser#250]
### Describe the bug

Within the SQL query box, enter a "DELETE" query. When simulating the query, JavaScript reports syntax error although the query is perfectly valid.

### To Reproduce

1. Go to tab SQL
2. Enter this query ``"DELETE FROM `sometable` WHERE 1 ORDER BY `column` ASC LIMIT 100;"``
3. Hit 'Simulate Query'.
4. See error '...error near LIMIT 100 LIMIT 100'

### Server configuration

- phpMyAdmin version: 4.8.5

**Comment by williamdes** [comment]
Fixed by 4.3.2
