### ISSUE TITLE
Missing `left join` in UPDATE statement build

### ISSUE THREAD

**Issue by wheng82** [phpmyadmin/sql-parser#260]
Dear sqlparser developer: Hello

Thank you very much and your team for developing PHP myadmin / sql-parser, an excellent PHP parser component with SQL grammar, which has helped me solve a series of crud-related interface problems. At present, I have used the software provided by you to implement a select SQL statement to complete a table, turn pages, query, repair. Change, add, delete operations.

I found a requirement in the process of using, that is, tables for join can also implement the update function, I hope you can add the corresponding function here.

For example, I have a select statement

```sql
Select u.*, ud. nickname from user u left join user_detail ud on u. id = ud. user_id where u.del = 0
```

I hope that I can update the data of the join table when I update it, but the syntax of the join part will be lost when this sentence is translated into the update statement at present.

for example

```sql
Update user u left join user_detail UD on u.id = ud.user_id set ud.ip ='33' where u.id = 1
```

This statement becomes $parser - > statements [0] - > build () code after new parser ($sql)

```sql
UPDATE user `u`SET ud.ip ='33' WHERE u.id = 1
```

The join part is missing, and there is no join module under the document update state in the hope of being resolved.

Thanks very much! Best wishes for sql-parser!

**Comment by wheng82** [comment]
亲爱的sqlparser开发者： 您好
非常感谢您和您的团队开发出了phpmyadmin/sql-parser 这个优秀的php用sql语法分析组件，帮助我解决了一系列crud相关的接口问题，目前我已经使用您提供的软件实现了通过一条select sql语句，实现对一个表格完整的，翻页，查询，修改，添加，删除操作。
我在使用过程中发现了一个需求，那就是针对join的表也可以实现update的功能，希望您这边可以增加相应的功能。
比如我有一条select的语句
select u.*,ud.nickname from  user u left join user_detail ud on u.id = ud.user_id where u.del = 0
我希望在我更新的时候也能够正常更新连表的数据，但是目前这条语句再被翻译到update的语句时 join部分的语法会丢失
例如
update user u left join user_detail ud on u.id = ud.user_id set ud.ip ='33' where u.id = 1
这条语句经过 new parser($sql)  后 进行 $parser->statements[0]->build()  代码就变成了
UPDATE user `u` SET ud.ip = '33' WHERE u.id = 1
丢失了join部分，并且根据文档 update statement 下也没有join模块  希望能够得到解决
非常感谢！ 祝sql-parser 越来越棒！

**Comment by williamdes** [comment]
Hi @wheng82 
I am sorry we did forget to reply to you

**Comment by williamdes** [comment]
@devenbansod could you please have a look into it ?

**Comment by williamdes** [comment]
🏓
