### ISSUE TITLE
Parser gives a non numeric limit as a value

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/sql-parser#275]
```sql
(SELECT "e" FROM dual LIMIT 1)
UNION
(SELECT "ee" FROM dual LIMIT 1)
```
OR
```sql
(SELECT "e" FROM dual LIMIT 1)
```

`$analyzed_sql_results['statement']->limit`
```json
{"offset":0,"rowCount":")"}
```

Ref: https://github.com/phpmyadmin/phpmyadmin/issues/15347

**Comment by williamdes** [comment]
@devenbansod could you please have a look?

**Comment by devenbansod** [comment]
Sure, I will try to take a look. :+1: It did not look straight-forward in the first look, but I will take a closer look and let you know.

**Comment by devenbansod** [comment]
PR at #278 provides the fix for:
```
(SELECT "e" FROM dual LIMIT 1)
```
