### ISSUE TITLE
Lexer fails to detect "*" as a wildcard.

### ISSUE THREAD

**Issue by niconoe-** [phpmyadmin/sql-parser#288]
Hi guys, thank you for this impressive tool!

I have noticed that the Lexer is currently not able to flag the "*" operator as a wildcard, and will only flag it as an arithmetic operator.

I would like to know if it is correct, in your opinion, to consider that "*" is a wildcard if it is followed by (ignoring whitespaces and comments) any of the following:
- `FROM` keyword, like in _SELECT * FROM_
- `USING` keyword like in _DELETE table_name.* USING_
- a comma `,` like in _SELECT *, field_name FROM or in DELETE foo.*, bar USING_
- a closing parenthesis `)`, like in _COUNT(*)_

Otherwise, we should consider "*" as an arithmetic operator. Would you agree on this?

If yes, I would be happy to provide a PR ;).

Actually, on a project of mine, I really need to distinguish the wildcard from the arithmetic operator, that's why I encountered this little issue.
Thank you!

**Comment by williamdes** [comment]
Hi @niconoe-  
I agree that we could detect it as a wildcard
Can you open a PR from QA?
I think a lot of tests will be needed to cover most cases 

We are glad that our tool is helpful for you!
