### ISSUE TITLE
Statement line number

### ISSUE THREAD

**Issue by Dzale** [phpmyadmin/sql-parser#304]
Hey guys, 

is there a way to get the actual line of statement that is currently being processed ? 

I need it for logging purposes, when i ignore some statement, i wanna know what line was it in file, 
so i can comeback later and check it.

Thanks in advance, and great package!

**Comment by williamdes** [comment]
Hi @Dzale 

Good question, maybe @devenbansod would know ?

> Thanks in advance, and great package!

Thank you !

**Comment by devenbansod** [comment]
@Dzale Unfortunately, we don't have the line number available *explicitly* while parsing. We do have access to the `$token` being processed and the `$token` does have information about the `position` (i.e. the start byte/char index) of the token in the input statement.

It might be possible to derive the line number given the char index. If you come up with a utility to do that, feel free to contribute it back to the library (possibly under [here](https://github.com/phpmyadmin/sql-parser/blob/master/src/Utils))

**Comment by Dzale** [comment]
Hey @devenbansod, 

thanks for quick response, ill check it out and see if i can come up with a solution.

**Comment by williamdes** [comment]
Any news here?

**Comment by drikusroor** [comment]
@Dzale or @williamdes have you ever been able to find a solution for this? 😇

**Comment by williamdes** [comment]
Re-opening this as it's an enhancement that can really be useful
