### ISSUE TITLE
testStdinPipe fails intermittently on s390x

### ISSUE THREAD

**Issue by bryceharrington** [phpmyadmin/sql-parser#309]
In Ubuntu, on s390x (only), we've been noticing occasional failures with CLITest::testStdinPipe in phpmyadmin-sql-parser version 4.6.1.  This test runs the php binary six times.  Out of five different CI runs:

    A: data set #2 and #5 failed
    B: data set #2 and #3 failed
    C: data set #1 and #3 failed
    D: data set #3 and #4 failed
    E: data sets #0, #1, #2, #3, #4, #5 all failed

https://autopkgtest.ubuntu.com/packages/phpmyadmin-sql-parser/groovy/s390x

In the cases where the CI passed, we weren't doing anything special, it seems to have just randomly passed.

I unfortunately don't have access to the s390x machine so am unable to investigate this directly, just via the CI system.  The php cli and test suite pass properly on my (non-s390x) hardware.  I'm hoping you may have some insights to help us make the test more deterministic?

**Comment by ibennetch** [comment]
Thanks for reporting this. I have no idea what could cause this, but we
will try to take a look and see if we can get anywhere with it.

**Comment by williamdes** [comment]
Thank you for reporting this here and on launchpad https://bugs.launchpad.net/phpmyadmin-sql-parser/+bug/1890341

Assigned to myself because I manage the packaging part

**Comment by williamdes** [comment]
Fixed by @sergiodj 
Will be in the next 4.x and 5.x releases
