### ISSUE TITLE
Linter accepts false syntax in view definitions

### ISSUE THREAD

**Issue by aszenz** [phpmyadmin/sql-parser#310]
Thanks for this wonderful library. 

It seems like the linter doesn't catch any syntax errors for the view definitions.

Running `./vendor/bin/lint-query --query "CREATE VIEW abc AS WRONG_SELECT a, b FROM a"` gives back no parsing errors even though the syntax is clearly wrong.

Tested on the latest version `5.3`, the older `4.1` version also had the same issue.

**Comment by williamdes** [comment]
Hi @aszenz 
Thank you !

We are lacking contributors and time to fix issues this month on this library, if you feel like opening a pull-request to `QA` branch we will be glad to welcome your contribution :)
