### ISSUE TITLE
simple example

### ISSUE THREAD

**Issue by Goddard** [phpmyadmin/sql-parser#313]
I was curious if any simple example existed to get just fields in the query and values associated with those fields?

**Comment by williamdes** [comment]
Maybe the README lacks some examples
https://github.com/phpmyadmin/sql-parser/blob/master/README.md#discoverying-query-type

**Comment by Goddard** [comment]
I saw this and it looks like it returns some information, but I was curious if an easy method existed to just grab fields and values.
This file looks like it has some reference to columns/values. https://github.com/phpmyadmin/sql-parser/blob/master/src/Components/SetOperation.php

For example this very simplified class has methods that allow getting fields().
https://github.com/marcocesarato/PHP-Light-SQL-Parser/blob/master/src/LightSQLParser.php

But I have found this class is too simplistic and often has issues with more complex statements.

I mainly want to use this SQL parser to log queries and get table, columns, and then values on modification type queries such as UPDATE/INSERT/DELETE etc..

Is the phpmyadmin sql parser a good solution for that?

Thanks

**Comment by williamdes** [comment]
> I mainly want to use this SQL parser to log queries and get table, columns, and then values on modification type queries such as UPDATE/INSERT/DELETE etc..
Is the phpmyadmin sql parser a good solution for that?

I think so, looks like some people already have done that.

**Comment by williamdes** [comment]
Also you can find good examples in https://github.com/phpmyadmin/sql-parser/tree/master/tests

**Comment by Goddard** [comment]
Thanks that helped.  Not sure if this is helpful to anyone, or even if it is absolutely the best way, but check this out.  Can I improve this? or is this probably the best way of doing it?
```
        $this->queries = array($testQuery, $testQuery2, $testQuery3, $testQuery4, $testQuery5);

        foreach ($this->queries as $query) {
            $fields = array();
            $values = array();
            $whereExpr = array();

            $parser = new Parser($query);
            foreach ($parser->statements as $statement) {
                var_dump(str_replace("`", "", Query::getTables($statement)));
                var_dump(Query::getFlags($statement)['querytype']);

                //insert update delete
                //insert statement->into->columns
                //insert statement->values
                if($statement instanceof InsertStatement) {
                    $fields = $statement->into->columns;
                    $values = $statement->values[0]->values;
                    var_dump($fields);
                    var_dump($values);
                }

                //update statement->set[]->column
                //update statement->set[]->value
                //update statement->where[]->isOperator == false (false dont get AND OR like operators)
                //update statement->where[]->identifiers [0] = column [1] = value not always present
                if($statement instanceof UpdateStatement || $statement instanceof DeleteStatement) {
                    if ($statement instanceof UpdateStatement) {
                        foreach ($statement->set as $set) {
                            array_push($fields, str_replace("`", "", $set->column));
                            array_push($values, trim($set->value, "'"));
                        }

                        var_dump($fields);
                        var_dump($values);
                    }

                    //delete statement->where[]->isOperator == false (false dont get AND OR like operators)
                    //delete statement->where[]->identifiers  [0] = column [1] = value not always present
                    foreach($statement->where as $where) {
                        if(!$where->isOperator) {
                            array_push($whereExpr, $where->expr);
                        }
                    }
                    var_dump($whereExpr);
                }
            }
        }
```

**Comment by williamdes** [comment]
Hi @devenbansod  
I think you know better than me the parser, could you please leave your advice?

**Comment by devenbansod** [comment]
Took a quick look. Looks okay to me. 

`Query::getFlags($statement)['querytype']` does provide a way to figure out what query type is present in a particular statement.

**Comment by williamdes** [comment]
Seems solved, closing :)
