### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/sql-parser#315]
When running the tests (`./vendor/phpunit/phpunit`) with PHP 8.0.0rc1, I get 41 errors. They all seem to relate to `ParseError: syntax error, unexpected token "match"`

For example,

```
1) PhpMyAdmin\SqlParser\Tests\Utils\CLITest::testRunHighlight with data set #0 (array('SELECT 1'), '^[[35mSELECT\n    ^[[92m1^[[0m\n', 0)
ParseError: syntax error, unexpected token "match"

/var/www/pma-dev/sql-parser/tests/Utils/CLITest.php:18
/var/www/pma-dev/sql-parser/tests/Utils/CLITest.php:55
```

**Comment by staabm** [comment]
In PHP 8 `match` is a reserved keyword.

**Comment by staabm** [comment]
Hmm I can not reproduce the error https://3v4l.org/kVnpM

**Comment by williamdes** [comment]
GitHub actions for PHP 8.0 did pass.
https://github.com/phpmyadmin/sql-parser/runs/1677406608?check_suite_focus=true#step:8:36
