### ISSUE TITLE
Missing comma before start of a new alter operation. (near "BY" at position 68) and Unrecognized alter operation. (near "BY" at position 68)

### ISSUE THREAD

**Issue by soumya1810** [phpmyadmin/sql-parser#316]
sql query written:
```sql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourRootPassword';
-- then
FLUSH PRIVILEGES;
```

**Comment by rounak-dev** [comment]
same problem, is there no other way  ??

**Comment by williamdes** [comment]
> same problem, is there no other way ??

Are you using phpMyAdmin or the parser directly?

**Comment by kipio** [comment]
I am getting this same error, can you help?
![MYSQL error](https://user-images.githubusercontent.com/88551867/135565070-728887b2-93b9-46c1-9466-83acb1a01030.png)

**Comment by kipio** [comment]
I managed to change the password of a user with the following query:

SET PASSWORD FOR 'root'@'localhost' = 'magento2';

Reference:
[https://dev.mysql.com/doc/refman/8.0/en/set-password.html](https://dev.mysql.com/doc/refman/8.0/en/set-password.html)

But still I would like to know why it is showing error for the statement:
ALTER USER 'root'@'localhost' IDENTIFIED BY 'magento2';

**Comment by niconoe-** [comment]
I don't know if you were running that on an non-rebased branch or something, but I just run that command on `master` branch today:
```bash
php ./bin/lint-query --query "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourRootPassword';
-- then
FLUSH PRIVILEGES;"
```

and everything worked like a charm.

@williamdes Can you double check that being sure you're on the latest version?

**Comment by williamdes** [comment]
> I don't know if you were running that on an non-rebased branch or something, but I just run that command on `master` branch today:
> 
> ```shell
> php ./bin/lint-query --query "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'YourRootPassword';
> -- then
> FLUSH PRIVILEGES;"
> ```
> 
> and everything worked like a charm.
> 
> @williamdes Can you double check that being sure you're on the latest version?

This command outputs nothing on 5.x and 6.x
What does it throw on your end ?

**Comment by niconoe-** [comment]
It output nothing neither on my side, which means there are no parsing error, which is the expected behavior. The query, and thoses statements, are correct.

**Comment by williamdes** [comment]
I think it's now fixed
@soumya1810 could you confirm with the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) ?
