### ISSUE TITLE
Parser fails when using some keywords as column names

### ISSUE THREAD

**Issue by elliot2extreme** [phpmyadmin/sql-parser#317]
Parsing the following statement will result in an error
```php
new Parser('ALTER TABLE `demo` ADD KEY `IDX_REPAIR` (`REPAIR`);', true);
```

Problem is the check
```php
elseif (! empty(Parser::$STATEMENT_PARSERS[$token->value]))
```
in the parse function in AlterOperation class. But as far as I understand it is allowed to use keywords as column names if you quote them.

How can we fix the problem? The easiest would be just to remove the check in the parse function. Another one would be to add an additional attribute to a token which tells if it was quoted. In case this is true, keywords are allowed as names and we skip the additional statement error checks in the parser for that token. What do you think?

**Comment by williamdes** [comment]
>  Another one would be to add an additional attribute to a token which tells if it was quoted. In case this is true, keywords are allowed as names and we skip the additional statement error checks in the parser for that token. What do you think?

I agree, feel free to make a pull-request to QA branch for that ;)

Could you paste the error here for the record please ?

**Comment by elliot2extreme** [comment]
```PhpMyAdmin\SqlParser\Tests\Parser\KeywordTokenTest::testKeywordWithQuotes
PhpMyAdmin\SqlParser\Exceptions\ParserException: A new statement was found, but no delimiter between it and the previous one.

/projects/sql-parser/src/Parser.php:607
/projects/sql-parser/src/Components/AlterOperation.php:287
/projects/sql-parser/src/Statements/AlterStatement.php:124
/projects/sql-parser/src/Statement.php:94
/projects/sql-parser/src/Parser.php:501
/projects/sql-parser/src/Parser.php:373
/projects/sql-parser/tests/Parser/KeywordTokenTest.php:15```
