### ISSUE TITLE
'",": Unrecognized alter operation' when altering table with ALGORITHM and LOCK clauses

### ISSUE THREAD

**Issue by PierreKerschgens** [phpmyadmin/sql-parser#319]
HI!

Despite I'm using your sql-parser as part of [php-sqllint](https://github.com/cweiske/php-sqllint) I think the following issue origins from sql-parser.

I have the following statement:

`ALTER TABLE XXX DROP COLUMN YYY, ALGORITHM=INPLACE, LOCK=NONE;`

Which results in the following false-positive:

` Line 9, col 65 at ",": Unrecognized alter operation.`
` Line 9, col 67 at "LOCK": A new statement was found, but no delimiter between it and the previous one.`
` Line 9, col 67 at "LOCK": Unrecognized alter operation.`

best regards!

**Comment by williamdes** [comment]
Hi @PierreKerschgens 
Thank you for the report !

**Comment by williamdes** [comment]
I added new tests in 6bdb41dbbf744203e38bcb3b0b6ac0048c543d2f
Before I merge https://github.com/phpmyadmin/sql-parser/pull/440 to fix this issue
