### ISSUE TITLE
Please add ContextMariaDb100500

### ISSUE THREAD

**Issue by nukdokplex** [phpmyadmin/sql-parser#328]
phpMyAdmin doesn't work on Windows with installed MariaDB 10.5.8 at all. Can anyone do something?

**Comment by ibennetch** [comment]
@phpmyadmin/developers shouldn't sql-parser inherit the common default context if the specific one is missing? However, we do seem to be missing both 100400 and 100500.

**Comment by ibennetch** [comment]
@nukdokplex Could you please tell me a little more about your configuration? Which Windows version, which phpMyAdmin version, and how have you installed MariaDB and phpMyAdmin? This seems to be a Windows specific problem because I can run that version of MariaDB on my Linux test host without trouble, so I'd like to try to recreate your environment for my Windows test.

**Comment by nukdokplex** [comment]
@ibennetch I don't think it's that important at all, but okay.
Windows 10 20H2 (19042.804)
PHP 8.0.2 with all required modules
MariaDB 10.5.8
phpMyAdmin 5.0.4
All binaries are official, not modified.
phpMyAdmin alerting a missing ContextMariaDb100500 and 100508.

**Comment by nukdokplex** [comment]
Sorry, @williamdes, I can't do this for now 'cause my dev machine doesn't have XAMPP installed. I migrated to WEMP stack. But the question is still open 'cause now a lot of webserver admins migrating to MariaDB 10.5.x and phpMyAdmin really needed to support it.

**Comment by williamdes** [comment]
> Sorry, @williamdes, I can't do this for now 'cause my dev machine doesn't have XAMPP installed. I migrated to WEMP stack. But the question is still open 'cause now a lot of webserver admins migrating to MariaDB 10.5.x and phpMyAdmin really needed to support it.
> Your contexts not updated about 11 months.

Well I use MariaDB 10.5 and phpMyAdmin 5.1 without any issues, ever
Did I miss something ?

**Comment by nukdokplex** [comment]
@williamdes so then why you cannot just clone context 100400 to 100500 if them is fully compatible?

**Comment by williamdes** [comment]
> @williamdes so then why you cannot just clone context 100400 to 100500 if them is fully compatible?

I am not against adding the context ;)
I just want to know how you reproduce the error using version 5.1.1 so I can also reproduce it and understand better the problem

**Comment by williamdes** [comment]
Hi @nukdokplex 

Done, I also added some documentation block for other members to know how to add contexts
Will be trying to improve this process
Still not understanding how you had the warning message
