### ISSUE TITLE
ALTER statement is not constructed properly by the parser

### ISSUE THREAD

**Issue by 007durgesh219** [phpmyadmin/sql-parser#33]
- var_dump of parser for the following query ```ALTER VIEW viewname AS SELECT * FROM tablename```

![alterview](https://cloud.githubusercontent.com/assets/7701929/13156956/2f7a1b72-d6ab-11e5-8994-7f0ffbad1b1c.png)

Here AlterStatement is NULL

- var_dump of ```ALTER TABLE abc ADD COLUMN a INT```

![altertable](https://cloud.githubusercontent.com/assets/7701929/13156980/58c5bfae-d6ab-11e5-9913-1e1080a74c50.png)

Here it won't detect the table name properly

Fix is required for the Tracker phpmyadmin/phpmyadmin#11966

**Comment by elrossco22** [comment]
@007durgesh219 I'm happy to look into this
