### ISSUE TITLE
[Question] Can I use this package to strip parameters from a query string?

### ISSUE THREAD

**Issue by halaei** [phpmyadmin/sql-parser#338]
Hello,
I need a tool that converts strings like
```sql
select * from `player_activity_logs` where `user_id` = 1234 and `action_type` = 2 and json_unquote(json_extract(`action_data`, '$."total_percent"')) > 20 and `context_type` not in (51, 32, 30, 60) and `item_source` = 1 and `item_type` != 2 order by `id` desc limit 200
```
into a string with ? as the parameters:
```sql
select * from `player_activity_logs` where `user_id` = ? and `action_type` = ? and json_unquote(json_extract(`action_data`, '$."total_percent"')) > ? and `context_type` not in (?, ?, ?, ?) and `item_source` = ? and `item_type` != ? order by `id` desc limit ?
```
My motivations are:
1. Prevent leak of sensitive information in logs.
2. Group identical queries with same structure but different parameters for performance reports.

I think I need a parser for that because maybe a simple regular expression doesn't work all the time. I just wondering if this package provides such a functionality or if I it gives me enough information to easily implement such a feature.
Thanks.

**Comment by williamdes** [comment]
Hello @halaei 

I am pretty sure you can do this, you can try exploring a Parsed select statement ?

You can see the parsed expression: https://github.com/phpmyadmin/sql-parser/blob/51ba37c199c238a62de2e1075fd97afb8d19470c/tests/data/parser/parseSelect.out#L1233
Query: https://github.com/phpmyadmin/sql-parser/blob/master/tests/data/parser/parseSelect.in

You can find an example here: https://github.com/phpmyadmin/sql-parser/blob/51ba37c199c238a62de2e1075fd97afb8d19470c/tests/Parser/SelectStatementTest.php#L12


Let me know if it helps :)

**Comment by halaei** [comment]
Thanks. I will work it out :)
