### ISSUE TITLE
Exporting table structure with COMPRESSED column - corrupt SQL

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/sql-parser#351]
As per phpmyadmin/phpmyadmin#14956, if we create a Table that contains one column that is "TEXT COMPRESSED", in MariaDB,
and then we do an Export, the CREATE TABLE statement will be corrupt, starting from the compressed column:

![image](https://user-images.githubusercontent.com/487079/107132219-079d3c80-68d5-11eb-9009-65f6f327bfb3.png)

And the "ALTER TABLE ADD KEY" statement that follows also didn't appear.

**Comment by linaspasv** [comment]
Any plans to fix this?

**Comment by williamdes** [comment]
> Any plans to fix this?

Hi @iifawzi
Do you want to contribute to this one?

**Comment by iifawzi** [comment]
Hi @williamdes, i’m a little bit busy now days, I might be able to look on it after the mid of July

**Comment by williamdes** [comment]
> Hi @williamdes, i’m a little bit busy now days, I might be able to look on it after the mid of July

Sure, no worries
You should apply for GitHub sponsors so I can sponsor you ;)

**Comment by iifawzi** [comment]
> > Hi @williamdes, i’m a little bit busy now days, I might be able to look on it after the mid of July
> 
> Sure, no worries You should apply for GitHub sponsors so I can sponsor you ;)

Thank you, unfortunately, it’s not supported in Egypt yet. 

I might consider applying as a contractor, if there’s a fit, later in September :”)

**Comment by williamdes** [comment]
> > > Hi @williamdes, i’m a little bit busy now days, I might be able to look on it after the mid of July
> > 
> > 
> > Sure, no worries You should apply for GitHub sponsors so I can sponsor you ;)
> 
> Thank you, unfortunately, it’s not supported in Egypt yet.
> 
> I might consider applying as a contractor, if there’s a fit, later in September :”)

Thank you for the PR!
I advise you to apply 2-3 months ahead ;)
