### ISSUE TITLE
DROP VIEW statement is not constructed properly by the parser

### ISSUE THREAD

**Issue by 007durgesh219** [phpmyadmin/sql-parser#36]
var_dump of parser for following query ```DROP VIEW abc```

![dropview](https://cloud.githubusercontent.com/assets/7701929/13352631/83150bb6-dcb4-11e5-8d30-d304ce233107.png)

Fix is required for phpmyadmin/phpmyadmin#11966

**Comment by nijel** [comment]
Fixed by https://github.com/phpmyadmin/sql-parser/pull/37
