### ISSUE TITLE
erroneously reports syntax error when calling stored procedure with schema

### ISSUE THREAD

**Issue by mousumis** [phpmyadmin/sql-parser#372]
### Describe the bug

The phpMyAdmin editor shows errors about tokens when running a call statement for stored procedure with the schema included. Example screenshot is included below

### To Reproduce

1. Go to phpMyAdmin
2. Click on the SQL tab
3. Run a stored procedure call script which includes a schema
4. Observe parsing errors though the command is correct and can execute correctly

### Expected behavior

No errors should be seen in the editor

### Screenshots
![image](https://user-images.githubusercontent.com/2347728/142443480-4f207e78-f2f7-434b-8265-6d1af5cb50f8.png)

### Server configuration

- Operating system: CentOS-7
- Web server: 
- Database version: 10.5.10-MariaDB
- PHP version: 7.4.24
- phpMyAdmin version: 4.9.7

### Client configuration

- Browser: Chrome
- Operating system: MacOS

**Comment by williamdes** [comment]
Thank you for the report, I moved it in the right place
