### ISSUE TITLE
Syntax error after logging in ContextMySql50700.php file?

### ISSUE THREAD

**Issue by phantom2152** [phpmyadmin/sql-parser#375]
Hey,

When I try to login to my php myadmin I get this parse error from php

`Parse error: syntax error, unexpected identifier "JSON_CONTAINS_PATH", expecting "]" in C:\localServer\Apache24\htdocs\phpMyAdmin\vendor\phpmyadmin\sql-parser\src\Contexts\ContextMySql50700.php on line 73`

 
![image](https://user-images.githubusercontent.com/70034285/161350305-3ea0859d-d1a5-40a6-bd58-c8d2542d79c0.png)

Can anyone help mw with this

**Comment by williamdes** [comment]
Hi @phantom2152 
From a syntax point of view https://github.com/phpmyadmin/sql-parser/blob/master/src/Contexts/ContextMySql50700.php is okay
What PHP version are you using ?
How did you install phpMyAdmin ?
What version is it ?

**Comment by phantom2152** [comment]
Php version is 8.1.2

I installed PhpMyAdmin Manually without xampp and have been using it for many days 

PhpMyAdmin Version  5.1.2 

I am attaching a photo of ContextMySql50700.php
 seems to be corrupted to me😅😅
![image](https://user-images.githubusercontent.com/70034285/161397878-98cb54dd-77b5-4039-a6d8-a5277eb61576.png)

**Comment by williamdes** [comment]
@ibennetch do you have an idea of what could be occurring?

**Comment by williamdes** [comment]
I am closing this one, this is most probably a corrupted unzip or FTP upload.
Is it solved @phantom2152 ?
