### ISSUE TITLE
Parser does not allow IS NULL in ORDER BY

### ISSUE THREAD

**Issue by Roryvdb** [phpmyadmin/sql-parser#396]
The following query leads to errors:
```sql
SELECT * FROM some_table
ORDER BY some_col IS NULL;
```
There is a workaround, by using parentheses:
```sql
SELECT * FROM some_table
ORDER BY (some_col IS NULL):
```
However, I think the first query should be allowed, as it is valid MySQL.

**Comment by williamdes** [comment]
Hi !
On what version did you try this query ?
