### ISSUE TITLE
Define multiple contexts

### ISSUE THREAD

**Issue by udan11** [phpmyadmin/sql-parser#4]
- ~~[ ] Drizzle 7.1~~
- ~~[ ] Drizzle 7.2~~
- [x] MariaDB 10.0
- [x] MariaDB 10.1
- [x] MariaDB 10.2
- [x] MySQL 5.0
- [x] MySQL 5.1
- [x] MySQL 5.5
- [x] MySQL 5.6
- [x] MySQL 5.7
- [x] MySQL 8.0

**Comment by nijel** [comment]
I don't think Drizzle support is needed. On the other side, there si MariaDB 10.1 missing in the list :-).
