### ISSUE TITLE
Wrong extraction of string with escaped quote

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/sql-parser#40]
Try parsing `SELECT '\''`. The extracted value is `\`, while it should be `'`. The bug is in `Token::extract` for `Token::TYPE_STRING`, it does just blindly replace `''` with single one, what is not right solution in this case.

**Comment by devenbansod** [comment]
I have been going through the code but can't seem to understand that why does it, in the first place, replace the `''` with a single `'`. Any pointers/specific example ?

**Comment by nijel** [comment]
```
MariaDB [(none)]> select '''';
+---+
| ' |
+---+
| ' |
+---+
1 row in set (0.00 sec)
```
