### ISSUE TITLE
"ALTER EVENT" is not recognized by the SQL parser

### ISSUE THREAD

**Issue by SanaRebhi** [phpmyadmin/sql-parser#404]
It seems that the latest release of sql-parser (5.6.0) does not support "ALTER EVENTS" yet.
The AlterOperation component needs to be updated in order to add all the options for the EVENT.
Any plans to handle this kind of statements please?

**Comment by williamdes** [comment]
Sure, thanks for reporting this :)

@iifawzi if you want to contribute :p

**Comment by iifawzi** [comment]
> Sure, thanks for reporting this :)
> 
> @iifawzi if you want to contribute :p

Sure, most probably by the end of the next week, I will get back on the track
