### ISSUE TITLE
'ALTER TABLE ... RENAME INDEX ...' statement not parsed correctly

### ISSUE THREAD

**Issue by nachopitt** [phpmyadmin/sql-parser#405]
Hello,

The following SQL statement is not parsed entirely by SQL Parser

```sql
ALTER TABLE `transactions` RENAME INDEX `fk_transactions_catalog_entries1_idx` TO `fk_transactions_catalog_entries2_idx`
```

It fails with the following message:

> Missing comma before start of a new alter operation. (near TO)

The same happens in PhpMyAdmin v5.2.0 as well:

![image](https://user-images.githubusercontent.com/12923928/210872151-7c2ed10e-ceae-43c4-8d83-3dcf039d0829.png)

Do you know what could be happening?

Thanks a lot!

**Comment by williamdes** [comment]
Hi!
A lot of work has been done on the SQL parser repository, could you test the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)? 

It should be fixed, if not let me know and we will have a look
