### ISSUE TITLE
`ALTER EVENT … RENAME TO new_db.new_event;` fails to be understood correctly by the parser

### ISSUE THREAD

**Issue by niconoe-** [phpmyadmin/sql-parser#419]
If you try to parse the following query:
```sql
ALTER EVENT my_old_event RENAME TO new_db.new_event;
```
the expression "new_db.new_event" fails to be understood correctly by the parser because the option `TO` on the event option is wrongly defined as "var" rather than "expr".

See: https://github.com/phpmyadmin/sql-parser/pull/420/files/090d759c1df5d31c65579234620718a13a013352#r1093700402

Related PR: https://github.com/phpmyadmin/sql-parser/pull/420

**Comment by niconoe-** [comment]
@williamdes As #420 is now merged, I don't know if you want to close this right now of if you want to prefer a new version to be released with this fix before.

**Comment by williamdes** [comment]
Ah, the PR missed a `Fixes: #419` line :/

**Comment by williamdes** [comment]
> @williamdes As #420 is now merged, I don't know if you want to close this right now of if you want to prefer a new version to be released with this fix before.

Normally PRs close issues and we milestone both of them
And one day there is a release of the changes ^^
