### ISSUE TITLE
Unexpeced token with REPLACE and parenthises 

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/sql-parser#43]
From http://stackoverflow.com/questions/35568587/phpmyadmin-4-5-4-unexpected-token-error-in-replace-statement

This query doesn't work with phpMyAdmin 4.5.5.1:
```
SELECT  *
FROM mytable
WHERE REPLACE (Col, 'a', '')  = 'bbb'
```

**Comment by udan11** [comment]
Hello,

I could not reproduce this in [master](http://demo.phpmyadmin.net/master-config/server_sql.php).

**Comment by nijel** [comment]
Strange, I can't reproduce even with 4.5.5.1...

**Comment by ibennetch** [comment]
Quite right, but the original report was about 4.5.4.1 where I can reproduce it. It must have been fixed already and I'm not sure anymore what I did to reproduce it originally that made me think it was still a bug. Normally I test this against master before posting, but perhaps I had a caching issue I missed. Thanks.

**Comment by q2apro** [comment]
I am running the latest Phpmyadmin 5.0.2 and get this:

![image](https://user-images.githubusercontent.com/6764548/92604201-ea7a2880-f2b8-11ea-886f-84125484c699.png)

With a correct query:

```
UPDATE `eventlog` 
SET `event` = 'u_registered' 
WHERE `event` = 'user_registered'
```

When clicking on "Simulate query" I get:

> #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'FROM `mr_eventlog` WHERE `event` = 'user_registered'' at line 1

Bug?!

<br>

**My server:**

Apache/2.4.46 (Unix)
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.3.21
