### ISSUE TITLE
DESCRIBE should allow schema.table

### ISSUE THREAD

**Issue by MoonE** [phpmyadmin/sql-parser#445]
```sql
DESC phpmyadmin.pma__users;
```
Results in an error:
> Unexpected beginning of statement (near pma__users)

Without  schema it works correctly:
```sql
DESC pma__users;
```

**Comment by williamdes** [comment]
Thank you @MoonE

**Comment by williamdes** [comment]
Hi @MoonE 
Could you test my changes (#446): `src/Statements/ExplainStatement.php` locally ?
