### ISSUE TITLE
Release 5.8.0

### ISSUE THREAD

**Issue by williamdes** [phpmyadmin/sql-parser#449]
I think everything is ready for me to make the 5.8.0 release.

cc @niconoe- @Tithugues @MauricioFauth @kamil-tekiela

It should occur in the following days except if someone has an objection

**Comment by kamil-tekiela** [comment]
Can we fix these errors? https://github.com/phpmyadmin/sql-parser/actions/runs/4965827219/jobs/8886885222

**Comment by williamdes** [comment]
> Oh, I think they are only on master branch, correct?

Yeah, I will fix them when I merge the 5.8.x branch

https://github.com/phpmyadmin/sql-parser/actions?query=branch%3A5.8.x ✅ All green !

**Comment by Tithugues** [comment]
Nobody has an objection! :grin:
