### ISSUE TITLE
FULLTEXT unrecognized data type

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/sql-parser#45]
Using this SQL from the MySQL manual:

`
CREATE TABLE opening_lines (
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
opening_line TEXT(500),
author VARCHAR(200),
title VARCHAR(200),
FULLTEXT idx (opening_line)
) ENGINE=InnoDB;`

I get a linter warning of "Unrecognized data type. (near idx)"

**Comment by nijel** [comment]
Fixed in git.
