### ISSUE TITLE
"closing bracket expected" when creating table

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/sql-parser#47]
When using the SQL query:

    CREATE TABLE MyGuests(
      id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    );

I get an warning "A closing bracket was expected. (Near **)**)"

Also, the characters `(` and `)` are technically parenthesis rather than brackets (which are `[` and `]`; braces are `{` and `}`), I wonder if we should improve the text of the notification.

**Comment by nijel** [comment]
```
./bin/lint-query --query "CREATE TABLE MyGuests(
>   id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
> );"
#1: A closing bracket was expected. (near ")" at position 72)
```

**Comment by nijel** [comment]
I think the linter is correct here, the SQL is invalid - there is extra ``,``. MySQL fails here as well:

```
> CREATE TABLE MyGuests( id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, );
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
```

**Comment by nijel** [comment]
Anyway there was place for improvement, so now it reports:

```
./bin/lint-query --query 'CREATE TABLE MyGuests(  `id` INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, );' 
#1: A symbol name was expected! (near ")" at position 73)
```

**Comment by ibennetch** [comment]
Thanks.
