### ISSUE TITLE
`ALTER TABLE … MODIFY … ENUM('<reserved_keyword>')` is being wrongly parsed.

### ISSUE THREAD

**Issue by niconoe-** [phpmyadmin/sql-parser#478]
When trying to parse a statement like this:

```sql
ALTER TABLE `MY_TABLE` 
MODIFY `FOO` INT(11) NULL,
MODIFY `MY_COLUMN` ENUM('INSERT','UPDATE','DELETE','REPLACE') NULL,
MODIFY `BAR` VARCHAR(255) NULL;
```

SQL-Parser fails because it considers each value of the enum as a real keyword, instead of a simple string. Hence, next operations on the `ALTER TABLE` statements are not understood correctly, and it makes fail the parser.
This causes:
```
#n: A new statement was found, but no delimiter between it and the previous one. (near "&#039;INSERT&#039;" at position xxx)
```

Thanks :slightly_smiling_face:

**Comment by Tithugues** [comment]
> Could be related to #450 and it's fix

Did I break something? :sweat_smile:

**Comment by williamdes** [comment]
Well, more tests are needed to know for sure ^^

**Comment by niconoe-** [comment]
> Ok, wait a minute, I screwed up something.
> 
> I just forgot to add the unit tests dataset I created sweat_smile . After actually adding them, the fix doesn't work.
> 
> That is because we are entering the `if(! empty(Parser::$statementParsers[$token->value]))` when doing the "SET", but not the "ENUM", and that is because "SET" **is also a statement keyword**, while "ENUM" is not…
> 
> We are just "lucky" to enter in this "if" block when using "SET" as a type, making no difference between "SET" as a type, and "SET" as a statement.
> 
> I'll fix that in a moment.

OK, that is fixed now. One of the side effect is that the tokens describing the `ENUM` are no longer stored in the `unknown` field, just like it was the case for the `SET`. So at least, both keywords are now producing the same behavior.

If that's an issue to not have the tokens in this case, I would suggest to create another issue IMO, as this also affected the `SET` type.
