### ISSUE TITLE
CREATE TABLE `table_copy` LIKE `table`;

### ISSUE THREAD

**Issue by SailorMax** [phpmyadmin/sql-parser#49]
Did not support creating copy of table by:
`CREATE TABLE 'table_copy' LIKE 'table';`

Output:
`An opening bracket was expected. (near: LIKE)` (after LIKE)
`At least one column definition was expected. (near:  )` (before LIKE)

**Comment by ibennetch** [comment]
Confirmed in 4.6.1 and 4.7.0-dev with parser 3.4.4.

Note that proper syntax should be backticks ` instead of the apostrophe/single quote ' but the error occurs even with backticks.
