### ISSUE TITLE
Missing support for COLLATE inside WHERE

### ISSUE THREAD

**Issue by BackEndTea** [phpmyadmin/sql-parser#491]
The following query results in 3 unexpected token errors, and 1 unrecognized keyword.

Is this intentional that this is considered an error?

```sql
SELECT  1
FROM   my_table
WHERE   first_col = ?
AND     second_col COLLATE utf8_bin = ?
```

Without the COLLATE everything is fine:

```sql
SELECT  1
FROM   my_table
WHERE   first_col = ?
AND     second_col = ?
```

**Comment by williamdes** [comment]
Hi,
It's probably something to be fixed or added for `COLLATE`

**Comment by BackEndTea** [comment]
I'll give this a try to fix

**Comment by williamdes** [comment]
The PR description should have closed it at merge time 🤔
