### ISSUE TITLE
Using `io` keyword as table alias fails to parse

### ISSUE THREAD

**Issue by BackEndTea** [phpmyadmin/sql-parser#496]
This first query fails to parse with `Unrecognized keyword`, `Unrecognized token` and `This type of clause was previously parsed` errors, while the second one has no issues

I get that using keywords as table aliases may not be the smartest, but this is valid SQL 😅 . Could sql-parser support this?

```sql
SELECT  COUNT(*) AS amount
FROM    one i
JOIN    two io ON io.id = i.id
```

```sql
SELECT  COUNT(*) AS amount
FROM    one i
JOIN    two ioo ON ioo.id = i.id
```

**Comment by williamdes** [comment]
That's weird, we should definitely support it. I am puzzled it's not already the case

**Comment by BackEndTea** [comment]
I'm currently running sql-parser against all queries inside of our code base. (which resulted in the issues i just opened). 

If you could give me some pointers to where i could roughly look to add support for this i'd be happy to do so

**Comment by williamdes** [comment]
Thank you!

Most probably in https://github.com/phpmyadmin/sql-parser/blob/master/src/Statements/SelectStatement.php
