### ISSUE TITLE
ALTER .. MODIFY ... ENUM failed! (Regression)

### ISSUE THREAD

**Issue by BorisValgo** [phpmyadmin/sql-parser#511]
Hi,

From the version 5.8.1 ALTER ENUM FAILD.
For example : 
`
ALTER TABLE users_type MODIFY limitations ENUM('tout', 'rien', 'bu', 'agence', 'agence_limite', 'n-1', 'agence_inactif');
UPDATE users_type SET limitations = 'agence_inactif' WHERE id_users_type = 19;`
When we user the 5.8.0 version the "lint-query --query" say OK but in 5.8.1 we have exception : 
`#1: A new statement was found, but no delimiter between it and the previous one. (near "UPDATE" at position 122)`

Thank you

**Comment by williamdes** [comment]
Released as [5.8.2](https://github.com/phpmyadmin/sql-parser/releases/tag/5.8.2)
