### ISSUE TITLE
Good idea

### ISSUE THREAD

**Issue by ximosa** [phpmyadmin/sql-parser#513]
I think it's an excellent idea to use an SQLite database, since for countless cases it is a good solution, and to be able to use WordPress for different types of websites and not kill flies with cannon fire, it would be interesting to create an implementation to install in Google cloud, I I installed on a micro instance and it is enough to work since the biggest resources are taken by mariadb and msql, I had to do it with a bitnami instance and then turn off the mariadb service and for now with the resources of a google cloud micro instance It is enough and for now free. Greetings and much encouragement.

**Comment by williamdes** [comment]
Hi @ximosa 

I translated your request into English.
I am not sure this has something to do with the sql-parser ?
Did you mean to report an issue ?
