### ISSUE TITLE
The executable files should be merged into a single executable file

### ISSUE THREAD

**Issue by MauricioFauth** [phpmyadmin/sql-parser#517]
This library currently ships with three executable files: `highlight-query`, `lint-query` and `tokenize-query`.

I propose that the three files should be combined into a single executable file called `sql-parser`.

```diff
-lint-query --query "SELECT 1"
+sql-parser --query "SELECT 1"
```

```diff
-lint-query --query "SELECT 1"
+sql-parser --lint --query "SELECT 1"
```

```diff
-highlight-query --query "SELECT 1"
+sql-parser --highlight --query "SELECT 1"
```

```diff
-tokenize-query --query "SELECT 1"
+sql-parser --tokenize --query "SELECT 1"
```

I think that `highlight-query`, `lint-query` and `tokenize-query` should be removed only in version 7.0.0.

**Comment by williamdes** [comment]
I'd say in 6.0?

**Comment by niconoe-** [comment]
AFAIK, this is done and is working like a charm.

Is there something else to do before closing this issue?
