### ISSUE TITLE
ALTER TABLE `table` COMMENT='Comment of table';

### ISSUE THREAD

**Issue by SailorMax** [phpmyadmin/sql-parser#53]
Did not support set comment to table:
`ALTER TABLE my_table COMMENT='Comment of table';`

Output:
`Unrecognized alter operation. (near: ;)`

**Comment by Subhani225** [comment]
Hi, I would like to contribute in fixing this bug.
I am a beginner to open source projects. 
So, I hope to get help from the experts in this project to fix the bug.
