### ISSUE TITLE
Properly flag queries as DROP DATABASE

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/sql-parser#54]
Currently several SQL queries are not properly flagged as DROP DATABASE:

* `` DROP SCHEMA IF EXISTS DBNAME``
* ``DROP /*! DATABASE */ DBNAME``
* ``DROP DATABASE`DBNAME` ``

**Comment by devenbansod** [comment]
The SQL Parser recognizes all of these correctly, but the flags set by SQL parser are not used correctly while flagging these queries.

Moved to https://github.com/phpmyadmin/phpmyadmin/issues/12531
