### ISSUE TITLE
Issue parsing « WITH PARSER `ngram` »

### ISSUE THREAD

**Issue by dugwood** [phpmyadmin/sql-parser#563]
It seems the parser has an issue with fulltext index with ngram, which throws an exception. I've seen it on phpmyadmin: foreign keys (that are defined after the fulltext) are missing on the table's relations page.

Simple example with:

```sql
CREATE TABLE `mytable` (
  `column_one` smallint unsigned DEFAULT NULL,
  FULLTEXT KEY `fulltext_index` (`column_one`) /*!50100 WITH PARSER `ngram` */,
  CONSTRAINT `my_constraint_1` FOREIGN KEY (`column_one`) REFERENCES `other_table` (`column_two`) ON DELETE RESTRICT ON UPDATE RESTRICT
)
```

Exception: `A comma or a closing bracket was expected.`
Exception debug for `->token`:
```
public 'token' => 
            object(PhpMyAdmin\SqlParser\Token)[1299]
              public 'token' => string 'WITH' (length=4)
              public 'value' => string 'WITH' (length=4)
              public 'keyword' => string 'WITH' (length=4)
              public 'type' => int 1
              public 'flags' => int 3
              public 'position' => int 128
```

**Comment by williamdes** [comment]
Thank you for reporting this @dugwood 

What do you think about it @iifawzi or @niconoe- ?

**Comment by niconoe-** [comment]
I'll try to take a look today.

**Comment by niconoe-** [comment]
@williamdes  / @iifawzi here you go :wink:
