### ISSUE TITLE
Non-reserved keywords should be allowed as a field name

### ISSUE THREAD

**Issue by Subhani225** [phpmyadmin/sql-parser#59]
Did not support set 'action' when creating a table prior to create a trigger:
"action varchar(50) default null"

Output:
A symbol name was expected! (near action)

**Comment by devenbansod** [comment]
Could you paste the complete SQL that you are trying to execute ? 
Is 'action' a field name or something different ?

**Comment by nijel** [comment]
Not sure if I got @Subhani225 correctly, but this is what works in MySQL, but fails for us:

```
./bin/lint-query --query 'create table tttt (action varchar(50) default null)'
#1: A symbol name was expected! (near "action" at position 19)
#2: At least one column definition was expected. (near "action" at position 19)
#3: Unexpected beginning of statement. (near "50" at position 34)
#4: Unrecognized statement type. (near "default" at position 38)
```
