### ISSUE TITLE
Please provide a Changelog

### ISSUE THREAD

**Issue by remicollet** [phpmyadmin/sql-parser#81]
Until 3.3.1, tag were documented (using the github feature).

No information about more recent versions.

See: http://keepachangelog.com/

**Comment by nijel** [comment]
I also wondered why we don't have one so far :-). I think it's better to do this in file rather than in GitHub releases....

**Comment by remicollet** [comment]
+1 for a file (rather than github feature)

**Comment by remicollet** [comment]
Great thanks!
